### ISSUE TITLE
Tests que necesitan más ♥

### ISSUE THREAD

**Issue by delucas** [Christian-VH-99/our-zork#10]
https://github.com/Christian-VH-99/our-zork/blob/39c5c11a62f4e02cae1aacc2e45895eee29af003/Zork/src/tests/PlaceTest.java#L11

Cuando no se necesita el contexto completo para una prueba, no generen más elementos de los necesarios.
Por otro lado, si utilizan el mecanismo de `@Before` (¡bien!), no repitan una parte del setup que está en todos los tests (¡mal!).

**Comment by facuegon481** [comment]
Se corrigió la generación de elementos de mas y solamente quedaron los elementos necesarios para las pruebas.

**Comment by delucas** [comment]
:+1:
