### ISSUE TITLE
Uso de operadores booleanos

### ISSUE THREAD

**Issue by delucas** [Christian-VH-99/our-zork#11]
https://github.com/Christian-VH-99/our-zork/blob/39c5c11a62f4e02cae1aacc2e45895eee29af003/Zork/src/Ubicacion/Conexion.java#L55-L62

Puede resolverse en una sola linea, con un bonito y elegante `&&`

**Comment by facuegon481** [comment]
Se resolvió con una sola linea

**Comment by delucas** [comment]
:+1:
