### ISSUE TITLE
Evitar utilizar String para todo

### ISSUE THREAD

**Issue by delucas** [Christian-VH-99/our-zork#12]
https://github.com/Christian-VH-99/our-zork/blob/39c5c11a62f4e02cae1aacc2e45895eee29af003/Zork/src/Ubicacion/Conexion.java#L7-L10

Probablemente podrían modelar estos atributos con objetos o enumerados

**Comment by facuegon481** [comment]
Se utilizó un ENUM para las direcciones

**Comment by delucas** [comment]
:+1:
