### ISSUE TITLE
Cohesión en los métodos

### ISSUE THREAD

**Issue by delucas** [Christian-VH-99/our-zork#13]
https://github.com/Christian-VH-99/our-zork/blob/39c5c11a62f4e02cae1aacc2e45895eee29af003/Zork/src/Ubicacion/Place.java#L91-L98

Cuando un método tiene una conjunción en el nombre, suele ser indicador de que está haciendo dos cosas a la vez. ¿Podría desagregarse dicha responsabilidad en dos métodos? ¿Podría renombrarse dicho método?
Revisen el codebase por nuevas ocurrencias de este tipo de problemas menores, que terminan enchastrando el código :)

**Comment by facuegon481** [comment]
Se renombró el método a un nombre mas significativo.

**Comment by delucas** [comment]
:+1:
