### ISSUE TITLE
Falta una combinación

### ISSUE THREAD

**Issue by delucas** [Christian-VH-99/our-zork#9]
https://github.com/Christian-VH-99/our-zork/blob/39c5c11a62f4e02cae1aacc2e45895eee29af003/Zork/src/tests/ItemTest.java#L12-L23

Puede parecer absurdo pero falta una combinación.
Adicionalmente, yo pondría cada una en un test separado, con nombres significativos (no `test`)

**Comment by facuegon481** [comment]
Se separó cada test en distintos con todas las combinaciones.

**Comment by delucas** [comment]
:+1:
